#!/usr/bin/env python
import os
import sys

# Standard godot-cpp GDExtension SCons build script
# Prerequisites: clone godot-cpp as a submodule or sibling directory
#   git clone --recursive https://github.com/godotengine/godot-cpp addons/simplex_noise_4d/godot-cpp
#
# Usage:
#   scons platform=windows target=editor           -> bin/windows/debug/simplex_noise_4d.dll
#   scons platform=windows target=template_release -> bin/windows/release/simplex_noise_4d.dll
#   scons platform=web target=template_release     -> bin/web/release/simplex_noise_4d.side.wasm

env = SConscript("godot-cpp/SConstruct")

# Append our source files
sources = Glob("src/*.cpp")

if "CPPPATH" not in env:
    env.Append(CPPPATH=["src/"])

file_prefix = ""
file_suffix = ""
file_ext = ".dll"

if env["platform"] == "web":
    file_ext = ".side.wasm"

target_name = "simplex_noise_4d"

if env["target"] == "editor":
    build_subdir = "debug"
else:
    build_subdir = "release"

if env["platform"] == "windows":
    platform_subdir = "windows"
elif env["platform"] == "web":
    platform_subdir = "web"
else:
    platform_subdir = env["platform"]

output_dir = os.path.join("bin", platform_subdir, build_subdir)
output_path = os.path.join(output_dir, target_name + file_ext)

env.Default(env.SharedLibrary(
    target=env.File(output_path),
    source=sources,
))
